services:
  - type: web
    name: agilechef
    env: static
    buildCommand: npm run build
    staticPublishPath: ./dist
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
      - path: /assets/*
        name: Cache-Control
        value: public, max-age=31536000, immutable
      - path: /assets/*.js
        name: Content-Type
        value: application/javascript
      - path: /assets/*.css
        name: Content-Type
        value: text/css
      - path: /assets/*.png
        name: Content-Type
        value: image/png
      - path: /assets/*.jpg
        name: Content-Type
        value: image/jpeg
      - path: /assets/*.svg
        name: Content-Type
        value: image/svg+xml
    routes:
      - type: rewrite
        source: /*
        destination: /index.html 